### ISSUE TITLE
sub BUILD does not get called

### ISSUE THREAD

**Issue by ufobat** [moose/MooseX-Singleton#1]
```
package MySingelton {
    use strict;
    use warnings;
    use Moose;
    use MooseX::Singleton;

    has has_build_run => (is => 'rw', default => 0);

    sub BUILD {
        my $self = shift;
        $self->has_build_run(1);
    }

    # if you make this immutable
    # sub build wont be called
    __PACKAGE__->meta->make_immutable;
};


my $instance = MySingelton->instance;
print $instance->dump;
```

**Comment by autarch** [comment]
I'm really not using this module any more, but I'd be happy to review a patch.

**Comment by slobo** [comment]
@autarch - because you don't use singletons any more or is there something with `MooseX::Singleton` in particular that keeps you away from it?

**Comment by autarch** [comment]
@slobo A little of both. I try to avoid singletons, but when I absolutely can't avoid them it's just as easy to just use a package-scoped global to store it. MX::Singleton is a bit hacky (as you've discovered re: this bug report).

**Comment by ufobat** [comment]
Maybe this is a duplicate 
https://rt.cpan.org/Public/Bug/Display.html?id=67645

**Comment by autarch** [comment]
@ufobat oh, I bet it is. I forgot that MX-Singleton is still using RT. I'm going to close this one.

**Comment by karenetheridge** [comment]
This is the only issue in the queue; I will change the settings to close github issues (which means this link will no longer be accessible, but we didn't discuss anything earthshaking in here anyway) :)
